# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7229ef6972023d1d5f47f3e60c54ea12aa6242bc6d335c7beacd1089098228975bb06d6a6829ef7d90ff3be253788371557e37f0d29ded8beda4f615b4c792

test:
  secret_key_base: 70bfb5bb25045749e36e22f4c3bf787487f35a0ca69116331c26a60bbe197165dc3954b62cc460ef4804a463b5d570e390c75935ed829cc34672e63c77d05e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
